<?php
/**
 * @file
 * Display random Dad jokes from https://icanhazdadjoke.com/.
 */

/**
 * Implements hook_block_info().
 */
function dadjoke_block_info() {
  $blocks['dadjoke'] = array(
    'info' => t('Dad joke'),
    'description' => t('A random Dad joke from https://icanhazdadjoke.com/.'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function dadjoke_block_view($delta = '', $settings = array(), $contexts = array()) {
  $block = array();

  // Get the stored Dad joke, or a random one.
  $joke = state_get('dadjoke') ?? get_dad_joke();

  // Format the output.
  if ($joke['error']) {
    $output = '<code>' . $joke['text'] . '</code>';
  }
  else {
    $output = '<p class="joke">' . $joke['text'] . '</p><p class="permalink"><a href="https://icanhazdadjoke.com/j/' . $joke['id'] . '">Permalink</a></p>';
  }

  switch ($delta) {
    case 'dadjoke':
      $block['subject'] = t('Random Dad joke');
      $block['content'] = $output;
      break;
  }

  return $block;
}

/**
 * Implements hook_cron().
 */
function dadjoke_cron() {
  // Get a random Dad joke and store it as a state value.
  $data = get_dad_joke();
  state_set('dadjoke', $data);
}

/**
 * Get a random Dad joke from https://icanhazdadjoke.com
 *
 * @return array
 *   An array containing the following key/value pairs:
 *   - text: The text to display (either the joke or an error message).
 *   - error: A boolean representing whether or not there was an error.
 *   - id: (optional) The joke ID (for permalinks).
 */
function get_dad_joke() {
  $joke = array();

  // Initialise API call.
  $curl = curl_init();
  curl_setopt($curl, CURLOPT_URL, 'https://icanhazdadjoke.com/');
  curl_setopt($curl, CURLOPT_HTTPHEADER, array(
    'Accept: application/json',
    "User-Agent: 'Dad Joke' Backdrop module (https://github.com/backdrop-contrib/dadjoke)",
  ));
  curl_setopt($curl, CURLOPT_RETURNTRANSFER, TRUE);

  // Make the API call.
  $response = curl_exec($curl);
  $code = curl_getinfo($curl, CURLINFO_RESPONSE_CODE);
  curl_close($curl);

  // Get the returned joke.
  if ($code < 400) {
    $data = json_decode($response, TRUE);

    if ($data['status'] == 200) {
      $joke['text'] = $data['joke'];
      $joke['error'] = FALSE;
      $joke['id'] = $data['id'];
    }
    else {
      $joke['text'] = "ERROR: The API call <em>returned</em> status code '" . $data['status'] . "'.";
      $joke['error'] = TRUE;
    }
  }
  else {
    $joke['text'] = "ERROR: The API call <em>failed</em> with status code '" . $code . "'.";
    $joke['error'] = TRUE;
  }

  return $joke;
}
